Feature/create form, added styles + validation
memx86/team-project-react pull request #12
Opened 2022-05-11 16:20 UTC by Persatyi

2022-05-11 17:54 UTC, memx86 requested changes

2022-05-11 20:22 UTC, Persatyi commented on src/components/AuthForm/AuthForm.jsx
> +            </div>
форму добавил

2022-05-11 20:23 UTC, Persatyi commented on src/components/AuthForm/AuthForm.jsx
> +              <label htmlFor="email"></label>
лишние теги поубирал

2022-05-11 20:23 UTC, Persatyi commented on src/components/AuthForm/AuthForm.jsx
> +                id="email"
исправлено

2022-05-11 20:25 UTC, Persatyi commented on src/components/AuthForm/AuthForm.module.scss
> +    text-transform: capitalize;
по макету placeholder с большой буквы

2022-05-11 20:44 UTC, Persatyi commented on src/components/AuthForm/AuthForm.module.scss
> +  top: calc(100% / 2 - 31px);
в процентах не пойдет, когда слишком длинная строка и идет перенос на следующую строку то позиция  ломается

2022-05-11 20:47 UTC, Persatyi commented on src/components/AuthForm/AuthForm.module.scss
> +  line-height: 1.5;
исправлено

2022-05-11 20:48 UTC, Persatyi commented on src/stylesheet/_base.scss
> +@use "./_mixin" as c;
исправлено

2022-05-11 20:51 UTC, Persatyi commented on src/components/AuthForm/AuthForm.module.scss
> +@use "../../stylesheet/mixin" as m;
буду знать, поправил

2022-05-12 06:31 UTC, memx86 approved these changes

2022-05-12 06:32 UTC, merged